apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-ci-demo-deployment
  labels:
    app: login-ci-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: login-ci-demo
  template:
    metadata:
      labels:
        app: login-ci-demo
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: login-ci-demo-container
        image: ruthik005/capstone_project:latest
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
        env:
        - name: SERVER_PORT
          value: "8081"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        # FIXED: Use root path instead of /actuator/health since actuator was removed
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 90  # Increased delay
          periodSeconds: 30
          timeoutSeconds: 10       # Added timeout
          failureThreshold: 5      # Added failure threshold
        readinessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 60  # Increased delay
          periodSeconds: 10
          timeoutSeconds: 5        # Added timeout
          failureThreshold: 3      # Added failure threshold
        securityContext:
          runAsUser: 1001
          runAsGroup: 1001
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
      volumes:
      - name: tmp-volume
        emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: login-ci-demo-service
  labels:
    app: login-ci-demo
spec:
  type: NodePort
  selector:
    app: login-ci-demo
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: login-ci-demo-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: login-demo.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: login-ci-demo-service
            port:
              number: 8081