apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-ci-demo-deployment
  labels:
    app: login-ci-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: login-ci-demo
  template:
    metadata:
      labels:
        app: login-ci-demo
    spec:
      # ** ADDED **: Harden the security context for the entire Pod
      securityContext:
        runAsNonRoot: true
      containers:
      - name: login-ci-demo-container
        image: ruthik005/capstone_project:latest
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp  # CORRECTED: Standard path for Spring Boot temp files
        env:
        - name: SERVER_PORT
          value: "8081"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
        # ** ADDED **: Harden the security context for the individual container
        securityContext:
          runAsUser: 1001             # Run as the 'appuser' UID
          runAsGroup: 1001            # Run as the 'appuser' GID
          readOnlyRootFilesystem: true  # Make the main filesystem read-only
          allowPrivilegeEscalation: false # Prevent gaining more privileges
      # ** MOVED & CORRECTED **: Define the writable temporary volume at the pod level
      volumes:
      - name: tmp-volume
        emptyDir: {}

---

# --- NO CHANGES BELOW THIS LINE ---

apiVersion: v1
kind: Service
metadata:
  name: login-ci-demo-service
  labels:
    app: login-ci-demo
spec:
  type: NodePort
  selector:
    app: login-ci-demo
  ports:
    - protocol: TCP
      port: 8081          # Internal cluster port
      targetPort: 8081    # Container port (matches your Dockerfile EXPOSE)
      nodePort: 30081     # External access port (you'll access via this)

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: login-ci-demo-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: login-demo.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: login-ci-demo-service
            port:
              number: 8081

