# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-ci-demo-deployment
spec:
  replicas: 2  # Run 2 copies of our application for availability
  selector:
    matchLabels:
      app: login-ci-demo
  template:
    metadata:
      labels:
        app: login-ci-demo
    spec:
      containers:
      - name: login-ci-demo-container
        # IMPORTANT: Use your Docker Hub image
        image: ruthik005/capstone_project:latest
        ports:
        - containerPort: 8081 # The port your Spring Boot app listens on