apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-ci-demo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-ci-demo
  template:
    metadata:
      labels:
        app: login-ci-demo
    spec:
      # ** NEW **: Harden the security context for the entire Pod
      securityContext:
        runAsNonRoot: true
      containers:
      - name: login-ci-demo-container
        image: ruthik005/capstone_project:latest
        ports:
        - containerPort: 8081
        
        # Harden the security context for the individual container
        securityContext:
          runAsUser: 1001             # Run as the 'appuser' UID we created
          runAsGroup: 1001            # Run as the 'appuser' GID we created
          readOnlyRootFilesystem: true  # Make the filesystem read-only
          allowPrivilegeEscalation: false # Prevent the container from gaining more privileges

