apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-ci-demo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-ci-demo
  template:
    metadata:
      labels:
        app: login-ci-demo
    spec:
      securityContext:
        runAsNonRoot: true
      # ** NEW **: Tells this Pod how to pull private images from Docker Hub
      imagePullSecrets:
      - name: regcred
      containers:
      - name: login-ci-demo-container
        image: ruthik005/capstone_project:latest # This will now be pulled using the 'regcred' secret
        ports:
        - containerPort: 8081
        securityContext:
          runAsUser: 1001
          runAsGroup: 1001
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false

