apiVersion: v1
kind: Config
clusters:
- name: default-cluster
  cluster:
    server: https://kubernetes.docker.internal:6443
    insecure-skip-tls-verify: true # Note: For production, you'd include a certificate instead.
contexts:
- name: default-context
  context:
    cluster: default-cluster
    user: jenkins
    namespace: default
current-context: default-context
users:
- name: jenkins
  user:
  token: eyJhbGciOiJSUzI1NiIsImtpZCI6InFmZDVnVHk4YlJNRGNQbDVmZDdDRjIwT0V5emxvOHdadGMzMmwwcEx1ckUifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzU2NTQ4NjA3LCJpYXQiOjE3NTY1NDUwMDcsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiMDViNjA5MDctNTY4OS00MTM5LTkwZGUtN2YyOGFmMTM5YTExIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkZWZhdWx0Iiwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImplbmtpbnMiLCJ1aWQiOiI5MTAxZjI0ZC04ODE4LTRjYmYtYmEwOC00MGNjZDgzZTAwZWMifX0sIm5iZiI6MTc1NjU0NTAwNywic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmRlZmF1bHQ6amVua2lucyJ9.UNiJcrn4YReJZuXgp3skCSXrmMLs5pzm-2rrQoQSroBZPH2mAGbmeIViue6bM5DiPgAJAlgslGscfY-IrZFtqSBcLPMTRkvl9_f2HHFYPmQUqG5sGVe3VBERs9kvsXnQRKChY97I7VHKm_-ZBFBzhTb-wghoW-2xfgQM9-lFN1vdgskeVZJAz8PWWFfPd5wNkfd1X7vKaB0RMjgY7JwHh-V71HojBCb8usjnE1WytLLVQJj84PsVMKkbT_UyVNBVJu7FVlp6i3ZzzKxTBwiYYrvf2wuhjVUrbXwgziVNU7QiKLIapeJ-J87sXeNCtYnc9IRlrNIKjCfA8iPxfm7KXA
